#ifndef INSTRUCIION__H
#define INSTRUCTION__H


#define INSTRUCTION_OPCODE_MASK 0xfc000000
#define INSTRUCTION_OPCODE_SHIFT 26

/* R-Type */
#define INSTRUCTION_RTYPE_RS_MASK 0x03e00000
#define INSTRUCTION_RTYPE_RS_SHIFT 21
#define INSTRUCTION_RTYPE_RT_MASK 0x001f0000
#define INSTRUCTION_RTYPE_RT_SHIFT 16
#define INSTRUCTION_RTYPE_RD_MASK 0x0000f800
#define INSTRUCTION_RTYPE_RD_SHIFT 11
#define INSTRUCTION_RTYPE_SA_MASK 0x000007c0
#define INSTRUCTION_RTYPE_SA_SHIFT 6
#define INSTRUCTION_RTYPE_FUNCTION_MASK 0x0000003f
#define INSTRUCTION_RTYPE_FUNCTION_SHIFT 0

/* J-Type */
#define INSTRUCTION_JTYPE_INST_INDEX_MASK 0x03ffffff
#define INSTRUCTION_JTYPE_INST_INDEX_SHIFT 0

/* I-Type */
#define INSTRUCTION_ITYPE_RS_MASK 0x03e00000
#define INSTRUCTION_ITYPE_RS_SHIFT 21
#define INSTRUCTION_ITYPE_RT_MASK 0x001f0000
#define INSTRUCTION_ITYPE_RT_SHIFT 16
#define INSTRUCTION_ITYPE_IMMEDIATE_MASK 0x0000ffff
#define INSTRUCTION_ITYPE_IMMEDIATE_SHIFT 0


typedef unsigned int instruction_t;

unsigned short INSTRUCTION_getOpcode(instruction_t);
unsigned short INSTRUCTION_getRs(instruction_t);
unsigned short INSTRUCTION_getRt(instruction_t);
unsigned short INSTRUCTION_getRd(instruction_t);
unsigned short INSTRUCTION_getFunction(instruction_t);
short INSTRUCTION_getImmediate(instruction_t);

#endif